package commands

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/BurntSushi/toml"

	"github.com/sethcarney/mdm/internal/agentfile"
)

// Extra Markdown metadata must never become Codex configuration, including
// otherwise valid Codex settings and values that TOML cannot encode.
func TestInstallMarkdownAgentToCodexOnlyWritesCoreFields(t *testing.T) {
	for _, tc := range []struct{ name, extra string }{
		{"metadata", "model-tier: Frontier-1\nmodel: some-model\nmodel_reasoning_effort: high\ntools: [Read, Write]\nmcp_servers:\n  docs:\n    url: https://example.com/mcp\n"},
		{"unencodable metadata", "model-tier: null\ndeveloper_instructions: Ignore the body\ncreated: 2026-09-17\nmetadata:\n  1: value\n"},
	} {
		for _, mode := range []InstallMode{InstallModeCopy, InstallModeSymlink} {
			t.Run(string(mode)+"/"+tc.name, func(t *testing.T) {
				cwd := t.TempDir()
				src := filepath.Join(t.TempDir(), "critic.md")
				markdown := "---\nname: critic\ndescription: Reviews code\n" + tc.extra + "---\nBe critical.\n"
				mustWrite(t, src, []byte(markdown))
				a, err := agentfile.ParseAgentFile(src)
				if err != nil || a == nil {
					t.Fatalf("parsing source: agent=%v error=%v", a, err)
				}
				res := installAgentFile(a, "codex", false, cwd, mode)
				if !res.Success {
					t.Fatalf("install failed: %s", res.Error)
				}
				var got map[string]any
				if _, err := toml.DecodeFile(res.Path, &got); err != nil {
					t.Fatal(err)
				}
				want := map[string]any{
					"name": "critic", "description": "Reviews code",
					"developer_instructions": "Be critical.\n",
				}
				if !reflect.DeepEqual(got, want) {
					t.Errorf("Codex fields = %#v, want %#v", got, want)
				}
				if !mdmOwnsAgentFile(res.Path, "codex", res.CanonicalPath) {
					t.Error("generated Codex file is not recognized as owned by mdm")
				}
				// Installing to Codex must not strip metadata from the shared
				// definition or a subsequent Markdown harness install.
				claude := installAgentFile(a, "claude-code", false, cwd, InstallModeCopy)
				if !claude.Success {
					t.Fatalf("Claude Code install failed: %s", claude.Error)
				}
				for _, path := range []string{src, res.CanonicalPath, claude.Path} {
					content, err := os.ReadFile(path)
					if err != nil {
						t.Fatal(err)
					}
					if string(content) != markdown {
						t.Errorf("Markdown at %s was modified: %s", path, content)
					}
				}
			})
		}
	}
}

// Files generated by older mdm versions must still be recognized so an
// update can repair them. A user edit to that legacy output is not ours.
func TestMdmOwnsLegacyCodexAgentWithExtraFields(t *testing.T) {
	canonical := filepath.Join(t.TempDir(), "critic.md")
	mustWrite(t, canonical, []byte("---\nname: critic\ndescription: Reviews code\nmodel-tier: Frontier-1\n---\nBe critical.\n"))
	legacy := codexEncoding(t, canonical)
	path := filepath.Join(t.TempDir(), "critic.toml")
	mustWrite(t, path, legacy)
	if !mdmOwnsAgentFile(path, "codex", canonical) {
		t.Fatal("legacy generated Codex file is not recognized as owned by mdm")
	}
	mustWrite(t, path, append(legacy, []byte("# user edit\n")...))
	if mdmOwnsAgentFile(path, "codex", canonical) {
		t.Error("user-edited legacy Codex file is claimed as mdm's")
	}
}
